language: java

services:
  - mongodb

install:
  - ./gradlew assemble

script:
  - ./gradlew check

env:
  global:
    - GRADLE_OPTS=-Xmx256m

os:
  - linux

jdk:
  - oraclejdk9

notification:
  email: false

